config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get '/resume', to: 'front#resume'
    get '/portfolio', to: 'front#portfolio'
    get '/contact', to: 'front#contact'
    post '/send_email', to: 'front#send_email', as: :send_email
    get '/download', to: 'front#download_pdf'
    root to: 'front#index'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  validates :name, length: { maximum: 30 }, presence: true
  validates :email, format: { with: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i }
  validates :subject, length: { maximum: 20 }, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/front_controller.rb
# frozen_string_literal: true

class FrontController < ApplicationController
  before_action :set_i18n_locale_from_params
  def index; end

  def resume; end

  def portfolio; end

  def contact
    @contact = Contact.new
  end

  def send_email
    @contact = Contact.new(set_params)
    if !verify_recaptcha(model: @contact) && @contact.save
      ContactMailer.contact_email(@contact).deliver
      ContactMailer.to_me(@contact).deliver
      redirect_to(contact_path, notice: t('email.sent_notice'))
    else
      flash[:alert] = t('email.sent_alert')
      render action: :contact
    end
  end

  def download_pdf
    if params[:locale] == 'en'
      send_file "#{Rails.root}/app/assets/download/cv_en.pdf", type: "application/pdf", x_sendfile: true
    else
      send_file "#{Rails.root}/app/assets/download/cv_es.pdf", type: "application/pdf", x_sendfile: true
    end
  end
  

  private

  def set_params
    params.require(:contact).permit(:name, :email, :subject, :content)
  end

  def set_i18n_locale_from_params
    if params[:locale]
      if I18n.available_locales.map(&:to_s).include?(params[:locale])
        I18n.locale = params[:locale]
      else
        flash.now[:alert] = "#{params[:locale]} translation not available"
        logger.error flash.now[:alert]
      end
    end
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end
end

app/helpers/front_helper.rb
# frozen_string_literal: true

module FrontHelper
end

app/views/front/contact.html.haml
= render 'front/sections/content/contact/contact'

app/views/front/index.html.haml
= render 'front/sections/content/home/home'

app/views/front/portfolio.html.haml
= render 'front/sections/content/portfolio/portfolio'
:javascript
  startIsotope();

app/views/front/resume.html.haml
= render 'front/sections/content/resume/resume'

app/views/front/sections/content/_contact.html.haml
.row.nopadding.skin
  %section#title.nopadding
    .padding-50.wow.fadeInRight
      .row.nopadding
        .col-md-12.nopadding
          %h3.title-text Contacto
        .sub-description
          %h5.font-subtitle HARD-WORKING PERSON ON THE WAY TO THE SUCCESS...
          %p.font-p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id metus purus. Ut vulputate, est vel tincidunt mattis, orci neque iaculis lectus, et interdum quam felis vel tortor. Fusce ultrices dui quis nunc dignissim faucibus. Ut ac odio quis nibh viverra fringilla ac id nisi. Suspendisse tincidunt augue quis ligula cursus, non efficitur ligula faucibus. Mauris id neque maximus, tincidunt metus et, sodales nulla.
  %section#contacts-data
    .padding-50.wow.fadeInLeft
      .row.nopadding.contact-data
        .col-xs-12.col-sm-12.col-md-6
          .row
            .col-sm-3
              .font-subtitle
                Direccion:
            .col-sm-9.nopadding
              .font-p
                direccion extra extra extra larga direccion extra extra extra larga
          .row
            .col-sm-3
              .font-subtitle
                Telefono:
            .col-sm-9.nopadding
              .font-p
                +58 424 650 78 66
          .row
            .col-sm-3
              .font-subtitle
                Skype:
            .col-sm-9.nopadding
              .font-p
                correo_super@hotmail.com
        .col-xs-12.col-sm-12.col-md-6.wow.fadeInLeft
          .row
            .col-sm-3
              .font-subtitle
                Twitter:
            .col-sm-9.nopadding
              .font-p
                https://www.facebook.com/profile.php?id=100011558673748
          .row
            .col-sm-3
              .font-subtitle
                Facebook:
            .col-sm-9.nopadding
              .font-p
                https://www.facebook.com/profile.php?id=100011558673748
          .row
            .col-sm-3
              .font-subtitle
                Likedin:
            .col-sm-9.nopadding
              .font-p
                https://www.facebook.com/profile.php?id=100011558673748
  %section#contact-map
    .padding-50.wow.fadeInRight
      #map.map

app/views/front/sections/content/_content.html.haml
.container-fluid.nopadding
  #home-section
  #resume-section
  #portfolio-section
  #contact-section
  #feedback-section
  #payments-section

:javascript
  var  home = "#{j render 'front/sections/content/home'}"
  var resume = "#{j render 'front/sections/content/resume'}"
  var portfolio = "#{j render 'front/sections/content/portfolio'}"
  var contact = "#{j render 'front/sections/content/contact'}"
  var feedback = "#{j render 'front/sections/content/feedback'}"
  var payments = "#{j render 'front/sections/content/payments'}"

  $(window).on("load", function() {
    $('#home-section').append(home);
  });

  $('#home').click(function() {
    $('#home-section').append(home);

    $('#resume-section').html('');
    $('#portfolio-section').html('');
    $('#contact-section').html('');
    $('#feedback-section').html('');
    $('#payments-section').html('');
  });

  $('#resume').click(function() {
    $('#resume-section').append(resume);

    $('#home-section').html('');
    $('#portfolio-section').html('');
    $('#contact-section').html('');
    $('#feedback-section').html('');
    $('#payments-section').html('');
  });

  $('#portfolio').click(function() {
    $('#portfolio-section').append(portfolio);

    $('#home-section').html('');
    $('#resume-section').html('');
    $('#contact-section').html('');
    $('#feedback-section').html('');
    $('#payments-section').html('');
  });

  $('#contact').click(function() {
    $('#contact-section').append(contact);

    $('#home-section').html('');
    $('#resume-section').html('');
    $('#portfolio-section').html('');
    $('#feedback-section').html('');
    $('#payments-section').html('');
  });

  $('#feedback').click(function() {
    $('#feedback-section').append(feedback);
    
    $('#home-section').html('');
    $('#resume-section').html('');
    $('#contact-section').html('');
    $('#portfolio-section').html('');
    $('#payments-section').html('');
  });

  $('#payments').click(function() {
    $('#payments-section').append(payments);

    $('#home-section').html('');
    $('#resume-section').html('');
    $('#contact-section').html('');
    $('#portfolio-section').html('');
    $('#feedback-section').html('');
  });

app/views/front/sections/content/_feedback.html.haml
.row.nopadding.skin
  %section#title.nopadding
    .padding-50.wow.fadeInRight
      .row.nopadding
        .col-md-12.nopadding
          %h3.title-text Feedback
        .sub-description
          %h5.font-subtitle HARD-WORKING PERSON ON THE WAY TO THE SUCCESS...
          %p.font-p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id metus purus. Ut vulputate, est vel tincidunt mattis, orci neque iaculis lectus, et interdum quam felis vel tortor. Fusce ultrices dui quis nunc dignissim faucibus. Ut ac odio quis nibh viverra fringilla ac id nisi. Suspendisse tincidunt augue quis ligula cursus, non efficitur ligula faucibus. Mauris id neque maximus, tincidunt metus et, sodales nulla.

app/views/front/sections/content/_home.html.haml
.row.nopadding.skin
  .col-md-8.nopadding
    .padding-50.wow.fadeInDown
      .row.nopadding
        .col-md-12.nopadding
          %h3.title-text SOBRE MÍ
        .sub-description
          %h5.font-subtitle HARD-WORKING PERSON ON THE WAY TO THE SUCCESS...
          %p.font-p
            Customize your website as you want using different colors and 100% free fonts.
      .row.nopadding
        .col-md-4.nopadding
          .row
            .col-sm-2.col-md-3.sm-pdn
              %i.fab.fa-connectdevelop.fa-cs{"aria-hidden" => "true"}
            .col-sm-10.col-md-9.nw-padding
              %h5.font-subtitle CREATIVE
              %p.font-p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet hendrerit dolor, at lacinia mi.
        .col-md-4.nopadding
          .row
            .col-sm-2.col-md-3.sm-pdn
              %i.fab.fa-cloudscale.fa-cs{"aria-hidden" => "true"}
            .col-sm-10.col-md-9.nw-padding
              %h5.font-subtitle SELF-MOTIVATED
              %p.font-p Curabitur sit amet laoreet leo. Maecenas eget pulvinar arcu. Quisque fermentum nulla non urna placerat.
        .col-md-4.nopadding
          .row
            .col-sm-2.col-md-3.sm-pdn
              %i.fas.fa-tasks.fa-cs{"aria-hidden" => "true"}
            .col-sm-10.col-md-9.nw-padding
              %h5.font-subtitle PUNCTUAL
              %p.font-p Sed scelerisque elit eget eros consectetur varius. Suspendisse laoreet rhoncus pellentesque
  .col-md-4.nopadding.w-grey
    .padding-50.wow.fadeInRight
      %h3.title-text
        PERSONAL INFO
      .personal-data
        .font-subtitle
          NOMBRE:
        .font-p
          Nombre del Cliente
      .personal-data
        .font-subtitle
          FECHA DE NACIMIENTO:
        .font-p
          09/07/1990
      .personal-data
        .font-subtitle
          DIRECCIÓN:
        .font-p
          Direcccion extra extra extra extra extra extra larga extra extra extra extra extra extra larga
      .personal-data
        .font-subtitle
          TELEFONO:
        .font-p
          +58-123-345-54-99
      .personal-data
        .font-subtitle
          EMAIL:
        .font-p
          prueba@gmail.com
.row.nopadding.cyan
  .col-md-4.nopadding
    .padding-50.wow.fadeInRight
      %h3.title-text
        PRO. EXPERIENCE
      = render 'front/sections/content/carousel/pro_experience'
  .col-md-8.nopadding.blue
    .padding-50.wow.fadeInLeft
      %h3.title-text
        My Professional skills
      = render 'front/sections/content/carousel/pro_skills'

app/views/front/sections/content/_portfolio.html.haml
.row.nopadding.skin
  %section#title.nopadding
    .padding-50.wow.fadeInRight
      .row.nopadding
        .col-md-12.nopadding
          %h3.title-text Mi Portafolio
        .sub-description
          %h5.font-subtitle HARD-WORKING PERSON ON THE WAY TO THE SUCCESS...
          %p.font-p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id metus purus. Ut vulputate, est vel tincidunt mattis, orci neque iaculis lectus, et interdum quam felis vel tortor. Fusce ultrices dui quis nunc dignissim faucibus. Ut ac odio quis nibh viverra fringilla ac id nisi. Suspendisse tincidunt augue quis ligula cursus, non efficitur ligula faucibus. Mauris id neque maximus, tincidunt metus et, sodales nulla.

app/views/front/sections/content/_resume.html.haml
.row.nopadding.skin
  .col-md-12.nopadding
    .padding-50.wow.fadeInRight
      .row.nopadding
        .col-md-12.nopadding
          %h3.title-text Resumen
        .sub-description
          %h5.font-subtitle HARD-WORKING PERSON ON THE WAY TO THE SUCCESS...
          %p.font-p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id metus purus. Ut vulputate, est vel tincidunt mattis, orci neque iaculis lectus, et interdum quam felis vel tortor. Fusce ultrices dui quis nunc dignissim faucibus. Ut ac odio quis nibh viverra fringilla ac id nisi. Suspendisse tincidunt augue quis ligula cursus, non efficitur ligula faucibus. Mauris id neque maximus, tincidunt metus et, sodales nulla.
  .col-md-12.noppading.w-grey
    .padding-50.wow.fadeInDown
      %h3.title-text.text-center Cualidades Personales
      %p.font-p.text-center
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id metus purus.
      .row.nopadding
        .padding-50
          .col-md-3
            .row.text-center
              .col-md-12
                %i.fa.fa-cogs.fa-cs{"aria-hidden" => "true"}
              .col-md-12
                %h5.font-subtitle CREATIVE
                %p.font-p For extreme size changes, we may want to change the layout altogether, either through a separate style sheet or, more efficiently, through a CSS media query.
          .col-md-3
            .row.text-center
              .col-md-12
                %i.fa.fa-code.fa-cs{"aria-hidden" => "true"}
              .col-md-12
                %h5.font-subtitle SELF-MOTIVATED
                %p.font-p It is possible to shrink things proportionally and rearrange elements as necessary to make everything fit (reasonably well) as a screen gets smaller.
          .col-md-3
            .row.text-center
              .col-md-12
                %i.fa.fa-rocket.fa-cs{"aria-hidden" => "true"}
              .col-md-12
                %h5.font-subtitle PUNCTUAL
                %p.font-p Below we have a few examples of responsive Web design in practice today. For many of these websites, there is more variation.
          .col-md-3
            .row.text-center
              .col-md-12
                %i.fa.fa-line-chart.fa-cs{"aria-hidden" => "true"}
              .col-md-12
                %h5.font-subtitle MULTITASK
                %p.font-p One major problem that needs to be solved with responsive Web design is working with images. There are a number of techniques.

app/views/front/sections/content/contact/_contact.html.haml
#feedback.row.nopadding.skin
  .col-md-12.nopadding
    .padding-50
      .row.nopadding
        .col-md-12.nopadding
          %h3.title-text
            = t("views.content.contact.title")
        .sub-description
          %h5.font-subtitle
            = t("views.content.subtitle")
          %p.font-p
            = t("views.content.contact.p")
  .col-md-12.nopadding
    .padding-page-parts
      %h3.title-text.text-center
        = t("views.content.contact.subtitle")
      .sub-description-resume.text-center
        %h5.font-subtitle
          = t("views.content.sub")
        %p.font-p
          = t("views.content.contact.p_email")
        %p.line-red.text-center
  .col-md-12.nopadding
    .padding-50
      .row.nopadding
        .col-md-2
        .col-md-8.text-center
          = simple_form_for @contact, url: { action: "send_email" }, method: :post do |f|
            .form-group
              = f.input :name, required: true, label: false, input_html: {class: "feedback-data font-subtitle", placeholder: "#{ t('views.content.contact.name') }", maxlength: 30}
              = f.input :email, required: true, as: :email, label: false, input_html: {class: "feedback-data font-subtitle", placeholder: "Email", required: "required"}
              = f.input :subject, required: true, label: false, input_html: {class: "feedback-data font-subtitle", placeholder: "#{ t('views.content.contact.about') }", maxlength: 20}
              = f.input :content, required: true, as: :text, label: false, input_html: {class: "feedback-data font-subtitle", placeholder: "#{ t('views.content.contact.message') } ...."}
            .row
              .col-md-10
                - if action_name == 'contact'
                  = javascript_include_tag 'https://www.google.com/recaptcha/api.js?render=6LcI2XoUAAAAAFNVCA8l9Xs44pqX3OQVN8LK477j', defer: "defer", async: true
                  = invisible_recaptcha_tags ui: :invisible, ajax: true, script: false
              .col-md-2
                = f.button :submit,  "#{ t('views.content.contact.send') }", class: "btn btn-portfolio font-subtitle"
        .col-md-2
  .col-md-12.nopadding
    %section#contact-map
      .padding-50
        #map.map

app/views/front/sections/content/home/_home.html.haml
#home.row.nopadding.skin
  .col-md-8.nopadding
    #animation.padding-50
      .row.nopadding
        .col-md-12.nopadding
          %h3.title-text 
            = t("views.content.home.about.title")
        .sub-description
          %h5.font-subtitle
            = t("views.content.subtitle")
          %p.font-p
            = t("views.content.home.about.p")
      .row.nopadding
        .col-md-4.nopadding
          .row
            .col-sm-2.col-md-3.sm-pdn
              %i.fas.fa-tasks.fa-cs{"aria-hidden" => "true"}
            .col-sm-10.col-md-9.nw-padding
              %h5.font-subtitle
                = t("views.content.home.about.second_title.subtitle1")
              %p.font-p
                = t("views.content.home.about.second_title.p1")
        .col-md-4.nopadding
          .row
            .col-sm-2.col-md-3.sm-pdn
              %i.fab.fa-cloudscale.fa-cs{"aria-hidden" => "true"}
            .col-sm-10.col-md-9.nw-padding
              %h5.font-subtitle
                = t("views.content.home.about.second_title.subtitle2")
              %p.font-p
                = t("views.content.home.about.second_title.p2")
        .col-md-4.nopadding
          .row
            .col-sm-2.col-md-3.sm-pdn
              %i.fas.fa-hourglass-end.fa-cs{"aria-hidden" => "true"}
            .col-sm-10.col-md-9.nw-padding
              %h5.font-subtitle
                = t("views.content.home.about.second_title.subtitle3")
              %p.font-p
                = t("views.content.home.about.second_title.p3")
  .col-md-4.nopadding.w-grey
    .padding-50
      %h3.title-text
        = t("views.content.home.personal_info.title")
      .personal-data
        .font-subtitle
          = t("views.content.home.personal_info.name")
        .font-p
          Alirio Jose Diaz Sanchez
      .personal-data
        .font-subtitle
          = t("views.content.home.personal_info.location")
        .font-p
          Chile - Region Metropolitana - Santiago Centro
      .personal-data
        .font-subtitle
          = t("views.content.home.personal_info.email")
        .font-p
          aliriodiaz111@gmail.com
.row.nopadding.cyan
  .col-xs-12.col-sm-12.col-md-4.nopadding
    .padding-50
      %h3.title-text
        = t("views.content.home.pro_experience.title")
      = render 'front/sections/content/home/carousel/pro_experience'
  .col-xs-12.col-sm-12.col-md-8.nopadding.blue
    .padding-50
      %h3.title-text
        = t("views.content.home.pro_skills.title")
      = render 'front/sections/content/home/carousel/pro_skills'

app/views/front/sections/content/home/carousel/_pro_experience.html.haml
#carousel-experience.carousel-experience.carousel.slide{"data-ride" => "carousel"}
  %ol.carousel-indicators.customized-experience
    /%li.active{"data-slide-to" => "0", "data-target" => "#carousel-experience"}
    /%li{"data-slide-to" => "1", "data-target" => "#carousel-experience"}
    /%li{"data-slide-to" => "2", "data-target" => "#carousel-experience"}
  .carousel-inner{:role => "listbox"}
    .item.active
      .resume-exp
        .font-p
          2013 - 2014
        .font-subtitle
          A UNO TV CA
        .font-p
          = t("views.content.home.pro_experience.position1")
      .resume-exp
        .font-p
          2016 - 2017
        .font-subtitle
          SLICEGROUP
        .font-p
          = t("views.content.home.pro_experience.position2")
      .resume-exp
        .font-p
          2017 - present
        .font-subtitle
          FREELANCE
        .font-p
          FULL STACK

app/views/front/sections/content/home/carousel/_pro_skills.html.haml
#carousel-skills.carousel-skills.carousel.slide{"data-ride" => "carousel", "data-interval" => "false"}
  .carousel-inner{:role => "listbox"}
    .item.active
      .row
        .col-sm-4
          .c100.p85.center
            %span 85%
            .slice
              .bar
              .fill
          %h3.font-subtitle.text-center
            HTML5 / HAML
        .col-sm-4
          .c100.p85.center
            %span 85%
            .slice
              .bar
              .fill
          %h3.font-subtitle.text-center
            CSS/SASS
        .col-sm-4
          .c100.p80.center
            %span 80%
            .slice
              .bar
              .fill
          %h3.font-subtitle.text-center
            Git
    .item
      .row
        .col-sm-4
          .c100.p100.center
            %span 60%
            .slice
              .bar
              .fill
          %h3.font-subtitle.text-center
            RUBY ON RAILS
        .col-sm-4
          .c100.p65.center
            %span 45%
            .slice
              .bar
              .fill
          %h3.font-subtitle.text-center
            JAVASCRIPT
        .col-sm-4
          .c100.p15.center
            %span 15%
            .slice
              .bar
              .fill
          %h3.font-subtitle.text-center
            C++
    .item
      .row
        .col-sm-4
          .c100.p15.center
            %span 15%
            .slice
              .bar
              .fill
          %h3.font-subtitle.text-center
            JAVA
        .col-sm-4
          .c100.p15.center
            %span 15%
            .slice
              .bar
              .fill
          %h3.font-subtitle.text-center
            C#
  %a.left.carousel-control{"data-slide" => "prev", href: "#carousel-skills", role: "button"}
    %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
    %span.sr-only Previous
  %a.right.carousel-control{"data-slide" => "next", href: "#carousel-skills", role: "button"}
    %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
    %span.sr-only Next

app/views/front/sections/footer/_footer.html.haml
.container-fluid.bg-front.padding-down
  .padding-50.grey-scale
    .row
      .col-xs-12.col-sm-5.col-md-5.foot-pdng
        %h4.footer-text
          Alirio Diaz
        %p.font-p
          = t("views.footer.career")
        %p.font-p
          = t("views.footer.pro")
      .col-xs-12.col-sm-7.col-md-7.foot-pdng
        %h4.footer-text.text-center
          = t("views.footer.follow")
        .social.text-center
          %a.btn.btn-round.btn-clear.btn-github{href: "https://github.com/aliriods", target: "_blank"}
            %i.fab.fa-github
          %a.btn.btn-round.btn-clear.btn-linkedin{href: "https://www.linkedin.com/in/alirio-diaz-298314b8?trk=nav_responsive_tab_profile", target: "_blank"}
            %i.fab.fa-linkedin-in
    .row
      .col-xs-12.col-md-12.col-md-12.copyrights
        %p © 2019 Alirio Díaz

app/views/front/sections/header/_header.html.haml
#header.container-fluid.nopadding
  .row.nopadding
    .col-xs-12.col-md-5.col-lg-4.nopadding
      .background-header
        = image_tag("web-development.gif", class: "img-responsive img-personal")
    .col-xs-12.col-md-7.col-lg-8.bg-front.nopadding
      .row.nopadding
        .col-xs-10.col-md-10.col-lg-10.title-head
          %svg#logo
            %path
        .col-xs-2.col-md-2.col-lg-2.hvr-sweep-to-right.cv-icon.pd-off
          = link_to download_path do
            %i.fas.fa-file-download.fa-3x.cs-icon{"aria-hidden" => "true", title: "#{t('views.header.download_cv')}"}
      .row.nopadding
        .col-xs-12.col-md-12.sb-title-head
          %h3 
            = t("views.header.welcome")
            %span.txt-rotate{"data-period" => "1500", "data-rotate" => "[ \"Hello World!!\", \"BoB!!\", \"User!!\", \"Everyone!!\"]"}
      %ul.row.nopadding{id: "nav"}
        %li#home
          = link_to root_path do
            .col-xs-3.col-sm-3.menu-item.home.hvr-sink
              %i.fas.fa-home.fa-2x{"aria-hidden" => "true"}
              %span 
                = t("views.header.link_to.home")
        %li#resume    
          = link_to resume_path do
            .col-xs-3.col-sm-3.menu-item.resume.hvr-sink
              %i.fas.fa-user-graduate.fa-2x{"aria-hidden" => "true"}
              %span
                = t("views.header.link_to.summary")
        %li#portfolio
          = link_to portfolio_path do
            .col-xs-3.col-sm-3.menu-item.portfolio.hvr-sink
              %i.fas.fa-layer-group.fa-2x{"aria-hidden" => "true"}
              %span
                = t("views.header.link_to.portfolio")
        %li#contact
          = link_to contact_path do
            .col-xs-3.col-sm-3.menu-item.contact.hvr-sink
              %i.fas.fa-map-marked-alt.fa-2x{"aria-hidden" => "true"}
              %span
                = t("views.header.link_to.contact")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Portfolio
    = csrf_meta_tags
    = csp_meta_tag
    %meta{content: "MsGMviSmnIXYhLTdfcWpeGPmxKnZ9vCwSWZR-sPlGJs", name: "google-site-verification"}/
    = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyBxUMjJ7VRpIWiy56Gyl7WcJNxRwlb8D2I'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.boxed
    - if notice || alert
      .alert.alert-dismissible{:role => "alert", class: "alert-#{notice ? "success" : "danger"}"}
        %button.close{'aria-label' => 'Close', 'data-dismiss' => 'alert', :type => 'button'}
          %span{'aria-hidden' => 'true'} ×
        = notice || alert
    .rounding
      .dropdown
        %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          .fas.fa-globe-americas.fa-cs
          %span.caret
        %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
          %li.padding
            = link_to 'English', {locale: 'en'}, {class: "#{'select' if params[:locale] == 'en'}"}
          %li.padding
            = link_to 'Español', {locale: 'es'}, {class: "#{'select' if params[:locale] == 'es'}"}
    = render 'front/sections/header/header'
    = yield
    = render 'front/sections/footer/footer'